#!/usr/bin/env python

import sys

from selfie_manager.session_manager import session_manager
from rqt_gui.main import Main

plugin = 'session_manager'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))